settings = read_json('../tilt-settings.json', default={})

if settings.get("allow_k8s_contexts"):
  allow_k8s_contexts(settings.get("allow_k8s_contexts"))

yaml=helm(
         './helm',
         name='stakater-notify-slack',
         values=['values-local.yaml'])

print(yaml)

k8s_yaml(yaml)