load('ext://helm_resource', 'helm_resource', 'helm_repo')
load('ext://helm_remote', 'helm_remote')

settings = read_json('../tilt-settings.json', default={})
helm_registry_user = settings.get("helm_registry_user")
helm_registry_pwd = settings.get("helm_registry_pwd")

# if settings.get("allow_k8s_contexts"):
#   allow_k8s_contexts(settings.get("allow_k8s_contexts"))
allow_k8s_contexts('stakater-actions-runner-controller/kubernetes-default-svc:443/system:serviceaccount:stakater-actions-runner-controller:actions-runner-controller-runner-deployment')

# Add helm repos
helm_repo('stakater', 'https://stakater.github.io/stakater-charts')
# helm_repo('bitnami', 'https://charts.bitnami.com/bitnami')

# Install Pipelines Operator
pipelines_operator_namespace = "rh-openshift-pipelines-operator"

# local('helm registry login ghcr.io --username={} --password={}'.format(helm_registry_user, helm_registry_pwd))

# helm_remote(
#     'rh-openshift-pipelines-operator',
#     repo_name='oci://ghcr.io/stakater/charts'
#   )

# helm_remote(
#     'rh-openshift-pipelines-instance',
#     repo_name='oci://ghcr.io/stakater/charts'
#   )

update_settings (max_parallel_updates = 1, k8s_upsert_timeout_secs=100)  
# helm_resource(
#     'rh-openshift-pipelines-operator', 
#     'oci://ghcr.io/stakater/charts/rh-openshift-pipelines-operator'
# )

# helm_resource(
#     'rh-openshift-pipelines-instance', 
#     'oci://ghcr.io/stakater/charts/rh-openshift-pipelines-instance'
# )


local_resource(
    'rh-openshift-pipelines-operator', 
    cmd='helm install rh-openshift-pipelines-operator oci://ghcr.io/stakater/charts/rh-openshift-pipelines-operator'
    )
local_resource(
    'rh-openshift-pipelines-instance', 
    cmd='helm install rh-openshift-pipelines-instance oci://ghcr.io/stakater/charts/rh-openshift-pipelines-instance',
    resource_deps=[
        'operator'
    ])