load('ext://helm_resource', 'helm_resource', 'helm_repo')

settings = read_json('../tilt-settings.json', default={})
helm_registry_user = settings.get("helm_registry_user")
helm_registry_pwd = settings.get("helm_registry_pwd")

# if settings.get("allow_k8s_contexts"):
#   allow_k8s_contexts(settings.get("allow_k8s_contexts"))
allow_k8s_contexts('stakater-actions-runner-controller/kubernetes-default-svc:443/system:serviceaccount:stakater-actions-runner-controller:actions-runner-controller-runner-deployment')

# Add helm repos
helm_repo('stakater', 'https://stakater.github.io/stakater-charts')

# Install Pipelines Operator
pipelines_operator_namespace = "rh-openshift-pipelines-operator"
 
update_settings (max_parallel_updates = 1) 
helm_resource(
    'rh-openshift-pipelines-operator', 
    'oci://ghcr.io/stakater/charts/rh-openshift-pipelines-operator'
)


helm_resource(
    'rh-openshift-pipelines-instance', 
    'oci://ghcr.io/stakater/charts/rh-openshift-pipelines-instance'
)