settings = read_json('../../tilt-settings.json', default={})

if settings.get("allow_k8s_contexts"):
  allow_k8s_contexts(settings.get("allow_k8s_contexts").format())

k8s_yaml(helm(
    './helm',
    name='stakater-set-commit-status',
    values=['values-local.yaml']))

